name: build-checks

on:
  push:
  pull_request:

jobs:
  buildx-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration (docker/build)
        uses: docker/build-push-action@v6
        with:
          call: check
          context: .
          file: ./Dockerfile

  bake-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration (docker/bake)
        uses: docker/bake-action@v6
        with:
          files: docker-bake.hcl
          targets: validate-build
